service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        # Amazon Resource Name (ARN)
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/AuctionsTable

resources:
  # Cloudformation, AWS specific
  Resources:
    # logical ID
    AuctionsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: AuctionsTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              # S stands for string
              AttributeType: S
          KeySchema:
            # is the partition key
            - AttributeName: id
              KeyType: HASH
    
  
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
